language: python

python:
    - 2.7

matrix:
    include:
        - env: {TOX_ENV: py27cov, COVERAGE: 1, BLESSED: 1}
        - env: {TOX_ENV: py27, COVERAGE: 0, BLESSED: 0}

before_install:
    - "[ ! -z $COVERAGE ] && travis_retry pip install coveralls || true"

# To install dependencies, tell tox to do everything but actually running the
# test.
install:
    - travis_retry pip install -r requirements.txt
    - "[ ! -z $BLESSED ] && travis_retry pip install blessed"
    - travis_retry tox -e $TOX_ENV --notest

script: tox -e $TOX_ENV

# coveralls.io reporting, using https://github.com/coagulant/coveralls-python
# Only report coverage for one version.
after_success:
    - "[ ! -z $COVERAGE ] && coveralls || true"
